const CLEAR_FILTER = 'CLEAR_FILTER'
const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
const SET_LOADED_STATE = 'SET_LOADED_STATE'
const SET_PRODUCTS = 'SET_PRODUCTS'
const TOGGLE_FILTER = 'TOGGLE_FILTER'
const TOGGLE_MODAL = 'TOGGLE_MODAL'

export {
  CLEAR_FILTER,
  FILTER_PRODUCTS,
  SET_LOADED_STATE,
  SET_PRODUCTS,
  TOGGLE_FILTER,
  TOGGLE_MODAL
}
