const FILTER_PRODUCTS = "FILTER_PRODUCTS";
const TOGGLE_FILTER = "TOGGLE_FILTER";
const TOGGLE_MODAL = "TOGGLE_MODAL";
const UPDATE_PAGE = "UPDATE_PAGE";

export {
    FILTER_PRODUCTS,
    TOGGLE_FILTER,
    TOGGLE_MODAL,
    UPDATE_PAGE
}